import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import heroImage from "../../public/assets/hero.png";

import { db } from "@/services/firebaseConnection";
import { collection, getDocs } from "firebase/firestore";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

interface HomeProps {
  posts: number;
  comments: number;
}
export default function Home({ posts, comments }: HomeProps) {
  return (
    <>
      <Head>
        <title>"Tarefas + | Organize suas tarefas de forma fácil"</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.logoContent}>
            <Image
              className={styles.hero}
              src={heroImage}
              alt="Tarefas + Logo"
              priority
            />
          </div>

          <h1 className={styles.title}>
            Sistema feito para você organizar <br />
            suas estudos e tarefas
          </h1>

          <div className={styles.infoContent}>
            <section className={styles.box}>
              <span>+{posts} posts</span>
            </section>
            <section className={styles.box}>
              <span>+{comments} comentários</span>
            </section>
          </div>
        </main>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const commentRef = collection(db, "comments");
  const postRef = collection(db, "tasks");

  const commentSnapshot = await getDocs(commentRef);
  const postSnapshot = await getDocs(postRef);

  return {
    props: {
      posts: postSnapshot.size || 0,
      comments: commentSnapshot.size || 0,
    },
    revalidate: 60, // seria revalidada a cada 60 segundos
  };
};
